### PR TITLE
Update to support MaaS API 2.0

### PR DESCRIPTION
**Pull request by tpmullan**
In response to #21 

I started the update to support the current stable version of MaaS.  I am not really sure what direction should be taken with the pending rewrite from Ryan.  So I just based my work off of the rewrite and made sure the functions worked for the most part.  

I got a little stuck on the bootstrap portion.  Neither implementation made sense to me.  Personally I felt the bootstrap function should take advantage of the MaaS deploy not just start an already configured server.  Anyway I would like to see this project gain some traction so I figure I might as well make it work for my use case.

### CODE REVIEW

**Comment by jjasghar** [comment]
@tpmullan please don't worry about Ryan's refactor. I've gone ahead and closed it, please don't hesitate about building up this 2.0 support!

**Comment by tpmullan** [comment]
Okay I will submit another pull request that is based on the current master.  But I would like to note that this one based on the refactor seems to have most if not all of the same features and is much easier to change api versions since it is extracted into a class.  Is there a reason that the refactoring is being rejected?   I wouldn't mind continuing along this track and flushing out the features.

**Comment by jjasghar** [comment]
Ah ok, with how much changed in the API from 1 to 2, I figured @ryancragun 's work would be out of date. If there are portions you think that should be merged it to make your life easier, i can either merge it or you can copyapasta what you need into yours. I'm flexible here.

**Comment by tpmullan** [comment]
I changed the version of ruby so Travis would run the tests, but there are not many tests there.  So the part that I still have a question about is the bootstrap function.  Should it deploy a new node on MAAS then bootstrap it?  Other than that the basic functions are working.

**Comment by jjasghar** [comment]
Awesome! I'll do my best to verify this with a peer review. If someone else can quicker I'll trust that and merge. Thanks!

**Comment by jjasghar** [comment]
Have you seen a bunch of `yml` outputted when you run `knife maas server list`?

```shell
16:04:17 JJs-MacBook-Pro knife-maas > (tpmullan-master) be knife maas server list
- address_ttl: null
  architecture: amd64/generic
  blockdevice_set:
  - available_size: 0
    block_size: 4096
    filesystem: null
    id: 3
    id_path: /dev/sda
    model: Virtual disk
    name: sda
    partition_table_type: MBR
    partitions:
    - bootable: false
      device_id: 3
      filesystem: {fstype: ext4, label: root, mount_options: null, mount_point: /,
        uuid: 220a2c7e-8c6a-4aab-bba7-529a76ec60ff}
      id: 1
      path: /dev/disk/by-dname/sda-part1
      resource_uri: /MAAS/api/2.0/nodes/pehnbn/blockdevices/3/partition/1
      size: 21466447872
      system_id: pehnbn
      type: partition
      used_for: ext4 formatted filesystem mounted at /
      uuid: 01bcbd21-a1d2-4b1c-b23b-666edd5ba847
    path: /dev/disk/by-dname/sda
    resource_uri: /MAAS/api/2.0/nodes/pehnbn/blockdevices/3/
    serial: ''
    size: 21474836480
    system_id: pehnbn
    tags: [rotary]
    type: physical
    used_for: MBR partitioned with 1 partition
    used_size: 21471690752
    uuid: null
  boot_disk: null
  boot_interface:
    children: []
    discovered:
    - ip_address: 10.0.0.101
      subnet:
        active_discovery: false
        allow_proxy: true
        cidr: 10.0.0.0/24
        dns_servers: [8.8.8.8]
        gateway_ip: 10.0.0.1
        id: 2
        name: 10.0.0.0/24
        rdns_mode: 2
        resource_uri: /MAAS/api/2.0/subnets/2/
        space: space-0
        vlan: {dhcp_on: true, external_dhcp: null, fabric: fabric-1, fabric_id: 1,
          id: 5002, mtu: 1500, name: untagged, primary_rack: bwmtbe, resource_uri: /MAAS/api/2.0/vlans/5002/,
          secondary_rack: null, vid: 0}
    effective_mtu: 1500
    enabled: true
    id: 6
    links:
    - id: 41
      mode: auto
      subnet:
        active_discovery: false
        allow_proxy: true
        cidr: 10.0.0.0/24
        dns_servers: [8.8.8.8]
        gateway_ip: 10.0.0.1
        id: 2
        name: 10.0.0.0/24
        rdns_mode: 2
        resource_uri: /MAAS/api/2.0/subnets/2/
        space: space-0
        vlan: {dhcp_on: true, external_dhcp: null, fabric: fabric-1, fabric_id: 1,
          id: 5002, mtu: 1500, name: untagged, primary_rack: bwmtbe, resource_uri: /MAAS/api/2.0/vlans/5002/,
          secondary_rack: null, vid: 0}
    mac_address: 00:50:56:8a:4b:61
    name: ens160
    params: ''
    parents: []
    resource_uri: /MAAS/api/2.0/nodes/pehnbn/interfaces/6/
    system_id: pehnbn
    tags: []
    type: physical
    vlan: {dhcp_on: true, external_dhcp: null, fabric: fabric-1, fabric_id: 1, id: 5002,
      mtu: 1500, name: untagged, primary_rack: bwmtbe, resource_uri: /MAAS/api/2.0/vlans/5002/,
      secondary_rack: null, vid: 0}
  cpu_count: 1
  disable_ipv4: false
  distro_series: ''
  domain: {authoritative: true, id: 0, name: maas, resource_record_count: 1, resource_uri: /MAAS/api/2.0/domains/0/,
    ttl: null}
  fqdn: legal-bee.maas
  hostname: legal-bee
  hwe_kernel: ''
  interface_set:
  - children: []
    discovered:
    - ip_address: 10.0.0.101
      subnet:
        active_discovery: false
        allow_proxy: true
        cidr: 10.0.0.0/24
        dns_servers: [8.8.8.8]
        gateway_ip: 10.0.0.1
        id: 2
        name: 10.0.0.0/24
        rdns_mode: 2
        resource_uri: /MAAS/api/2.0/subnets/2/
        space: space-0
        vlan: {dhcp_on: true, external_dhcp: null, fabric: fabric-1, fabric_id: 1,
          id: 5002, mtu: 1500, name: untagged, primary_rack: bwmtbe, resource_uri: /MAAS/api/2.0/vlans/5002/,
          secondary_rack: null, vid: 0}
    effective_mtu: 1500
    enabled: true
    id: 6
    links:
    - id: 41
      mode: auto
      subnet:
        active_discovery: false
        allow_proxy: true
        cidr: 10.0.0.0/24
        dns_servers: [8.8.8.8]
        gateway_ip: 10.0.0.1
        id: 2
        name: 10.0.0.0/24
        rdns_mode: 2
        resource_uri: /MAAS/api/2.0/subnets/2/
        space: space-0
        vlan: {dhcp_on: true, external_dhcp: null, fabric: fabric-1, fabric_id: 1,
          id: 5002, mtu: 1500, name: untagged, primary_rack: bwmtbe, resource_uri: /MAAS/api/2.0/vlans/5002/,
          secondary_rack: null, vid: 0}
    mac_address: 00:50:56:8a:4b:61
    name: ens160
    params: ''
    parents: []
    resource_uri: /MAAS/api/2.0/nodes/pehnbn/interfaces/6/
    system_id: pehnbn
    tags: []
    type: physical
    vlan: {dhcp_on: true, external_dhcp: null, fabric: fabric-1, fabric_id: 1, id: 5002,
      mtu: 1500, name: untagged, primary_rack: bwmtbe, resource_uri: /MAAS/api/2.0/vlans/5002/,
      secondary_rack: null, vid: 0}
  ip_addresses: [10.0.0.101]
  memory: 2024
  min_hwe_kernel: ''
  netboot: true
  node_type: 0
  node_type_name: Machine
  osystem: ''
  owner: admin
  owner_data: {}
  physicalblockdevice_set:
  - available_size: 0
    block_size: 4096
    filesystem: null
    id: 3
    id_path: /dev/sda
    model: Virtual disk
    name: sda
    partition_table_type: MBR
    partitions:
    - bootable: false
      device_id: 3
      filesystem: {fstype: ext4, label: root, mount_options: null, mount_point: /,
        uuid: 220a2c7e-8c6a-4aab-bba7-529a76ec60ff}
      id: 1
      path: /dev/disk/by-dname/sda-part1
      resource_uri: /MAAS/api/2.0/nodes/pehnbn/blockdevices/3/partition/1
      size: 21466447872
      system_id: pehnbn
      type: partition
      used_for: ext4 formatted filesystem mounted at /
      uuid: 01bcbd21-a1d2-4b1c-b23b-666edd5ba847
    path: /dev/disk/by-dname/sda
    resource_uri: /MAAS/api/2.0/nodes/pehnbn/blockdevices/3/
    serial: ''
    size: 21474836480
    system_id: pehnbn
    tags: [rotary]
    type: physical
    used_for: MBR partitioned with 1 partition
    used_size: 21471690752
    uuid: null
  power_state: unknown
  power_type: manual
  resource_uri: /MAAS/api/2.0/machines/pehnbn/
  special_filesystems: []
  status: 10
  status_action: modules-final
  status_message: '''cloudinit'' running modules for final'
  status_name: Allocated
  storage: 21474.83648
  swap_size: null
  system_id: pehnbn
  tag_names: [virtual]
  virtualblockdevice_set: []
  zone: {description: '', id: 1, name: default, resource_uri: /MAAS/api/2.0/zones/default/}
- architecture: amd64/generic
  cpu_count: 1
  distro_series: xenial
  domain: {authoritative: true, id: 0, name: maas, resource_record_count: 1, resource_uri: /MAAS/api/2.0/domains/0/,
    ttl: null}
  fqdn: maas.maas
  hostname: maas
  interface_set:
  - children: []
    discovered:
    - ip_address: 172.16.20.154
      subnet:
        active_discovery: false
        allow_proxy: true
        cidr: 172.16.20.0/24
        dns_servers: []
        gateway_ip: null
        id: 1
        name: 172.16.20.0/24
        rdns_mode: 2
        resource_uri: /MAAS/api/2.0/subnets/1/
        space: space-0
        vlan: {dhcp_on: false, external_dhcp: 172.16.20.10, fabric: fabric-0, fabric_id: 0,
          id: 5001, mtu: 1500, name: untagged, primary_rack: null, resource_uri: /MAAS/api/2.0/vlans/5001/,
          secondary_rack: null, vid: 0}
    effective_mtu: 1500
    enabled: true
    id: 1
    links:
    - id: 1
      ip_address: 172.16.20.154
      mode: dhcp
      subnet:
        active_discovery: false
        allow_proxy: true
        cidr: 172.16.20.0/24
        dns_servers: []
        gateway_ip: null
        id: 1
        name: 172.16.20.0/24
        rdns_mode: 2
        resource_uri: /MAAS/api/2.0/subnets/1/
        space: space-0
        vlan: {dhcp_on: false, external_dhcp: 172.16.20.10, fabric: fabric-0, fabric_id: 0,
          id: 5001, mtu: 1500, name: untagged, primary_rack: null, resource_uri: /MAAS/api/2.0/vlans/5001/,
          secondary_rack: null, vid: 0}
    mac_address: 00:50:56:8a:4f:0f
    name: ens160
    params: ''
    parents: []
    resource_uri: /MAAS/api/2.0/nodes/bwmtbe/interfaces/1/
    system_id: bwmtbe
    tags: []
    type: physical
    vlan: {dhcp_on: false, external_dhcp: 172.16.20.10, fabric: fabric-0, fabric_id: 0,
      id: 5001, mtu: 1500, name: untagged, primary_rack: null, resource_uri: /MAAS/api/2.0/vlans/5001/,
      secondary_rack: null, vid: 0}
  - children: []
    discovered: null
    effective_mtu: 1500
    enabled: true
    id: 3
    links:
    - id: 23
      ip_address: 10.0.0.1
      mode: static
      subnet:
        active_discovery: false
        allow_proxy: true
        cidr: 10.0.0.0/24
        dns_servers: [8.8.8.8]
        gateway_ip: 10.0.0.1
        id: 2
        name: 10.0.0.0/24
        rdns_mode: 2
        resource_uri: /MAAS/api/2.0/subnets/2/
        space: space-0
        vlan: {dhcp_on: true, external_dhcp: null, fabric: fabric-1, fabric_id: 1,
          id: 5002, mtu: 1500, name: untagged, primary_rack: bwmtbe, resource_uri: /MAAS/api/2.0/vlans/5002/,
          secondary_rack: null, vid: 0}
    mac_address: 00:50:56:8a:65:21
    name: ens192
    params: ''
    parents: []
    resource_uri: /MAAS/api/2.0/nodes/bwmtbe/interfaces/3/
    system_id: bwmtbe
    tags: []
    type: physical
    vlan: {dhcp_on: true, external_dhcp: null, fabric: fabric-1, fabric_id: 1, id: 5002,
      mtu: 1500, name: untagged, primary_rack: bwmtbe, resource_uri: /MAAS/api/2.0/vlans/5002/,
      secondary_rack: null, vid: 0}
  ip_addresses: [10.0.0.1]
  memory: 4024
  node_type: 4
  node_type_name: Region and rack controller
  osystem: ubuntu
  power_state: unknown
  power_type: ''
  resource_uri: /MAAS/api/2.0/rackcontrollers/bwmtbe/
  service_set:
  - {name: regiond, status: running, status_info: ''}
  - {name: bind9, status: running, status_info: ''}
  - {name: ntp_region, status: running, status_info: ''}
  - {name: proxy, status: running, status_info: ''}
  - {name: ntp_rack, status: unknown, status_info: managed by the region.}
  - {name: dhcpd, status: running, status_info: ''}
  - {name: tftp, status: running, status_info: ''}
  - {name: dhcpd6, status: 'off', status_info: ''}
  - {name: http, status: running, status_info: ''}
  - {name: tgt, status: running, status_info: ''}
  - {name: rackd, status: running, status_info: ''}
  status_action: starting refresh
  swap_size: null
  system_id: bwmtbe
  zone: {description: '', id: 1, name: default, resource_uri: /MAAS/api/2.0/zones/default/}
16:04:21 JJs-MacBook-Pro knife-maas > (tpmullan-master) be knife maas server
FATAL: Cannot find subcommand for: 'maas server'
Available maas subcommands: (for details, knife SUB-COMMAND --help)

** MAAS COMMANDS **
knife maas server acquire (options)
knife maas server bootstrap (options)
knife maas server commission (options)
knife maas server delete (options)
knife maas server list
knife maas server release (options)
knife maas server show $NODE (options)
knife maas server start (options)
knife maas server stop (options)

16:04:46 JJs-MacBook-Pro knife-maas > (tpmullan-master) be knife maas server start legal-bee
ERROR: Not Found
16:05:06 JJs-MacBook-Pro knife-maas > (tpmullan-master) be knife maas server start legal-bee.maas
ERROR: Not Found
16:05:09 JJs-MacBook-Pro knife-maas > (tpmullan-master) be knife maas server show legal-bee
ERROR: KeyError: key not found: "F"
16:06:43 JJs-MacBook-Pro knife-maas > (tpmullan-master) be knife maas server show legal-bee.maas
ERROR: KeyError: key not found: "F"
16:06:50 JJs-MacBook-Pro knife-maas > (tpmullan-master)
```

**Comment by tpmullan** [comment]
My bad.  I left a debug log.  That is the raw data from the server.

**Comment by jjasghar** [comment]
I'm going to bump this to 2.0.0 and release. I was able to get it working and did what i expected. Thanks for all your work on it!

**Comment by jjasghar** [comment]
Released! https://twitter.com/rubygems/status/842491064024027136

**Pull request merged**
